---

- name: Create directory structure for application
  file:
    path: "{{ back_directory }}"
    state: directory
    owner: "{{ back_user }}"
    group: "{{ back_group }}"

- name: Upload docker-compose file
  template:
    src: templates/docker-compose.yml
    dest: "{{ back_directory }}/docker-compose.yml"
    owner: "{{ back_user }}"
    group: "{{ back_group }}"

- name: Start docker-compose project
  docker_compose:
    project_src: "{{ back_directory }}"
