version: "3.1"

services:
  api:
    image: "{{ back_docker_image }}:{{ back_docker_tag }}"
    working_dir: /home/app
    environment:
      DB_HOST: {{ back_mysql_host }}
      DB_USER: {{ back_mysql_user }}
      DB_PASSWORD: {{ back_mysql_password }}
      DB_NAME: {{ back_mysql_name }}
      JWT_TOKEN: ':g9{72mHiX38dK[C-M@(d7aDp2'
    ports:
      - "{{ back_port }}:3000"
    command: npm run start
