---
- name: Install python and docker
  hosts: all
  gather_facts: no
  roles:
  - { role: python, tags: ["python"] }
  - { role: geerlingguy.docker, tags: ["docker"] }

- name: Deploy docker-compose back
  import_playbook: back.yml
  tags: ['back']

- name: Deploy docker-compose web
  import_playbook: web.yml
  tags: ['web']
