version: "3.1"

services:
  front:
    image: "{{ web_docker_image }}:{{ web_docker_tag }}"
    ports:
      - "{{ web_port }}:3000"
    command: yarn run start
    environment:
      REACT_APP_API: {{ back_endpoint }}
